"""empty message

Revision ID: 7079492ec0c9
Revises: 9be920e8c3bb
Create Date: 2018-05-23 02:22:28.397265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7079492ec0c9'
down_revision = '9be920e8c3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_created_by_fkey', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('questions_created_by_fkey', 'questions', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
